- name: install nginx and start nginx
  host: 172.31.26.105
  become: yes # excute as root 
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - nmae: start nginx
    name: nginx
    state: started # to start the nginx
    enabled: yes 