- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install dependenices
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql
    - zip